#ifndef __YUNI_SCRIPT_SCRIPT_DEFINES_H__
# define __YUNI_SCRIPT_SCRIPT_DEFINES_H__

/*!
** \file
** Defines macros for method declaration in AScript & co.
** The macros in this file are used to declare functions with 
** various argument counts (bind() and call()) in AScript declaration,
** and declarations of all classes inheriting from it.
*/

# define YUNI_SCRIPT_SCRIPT_VARIANT(name) \
	const Variant & name

# define YUNI_SCRIPT_SCRIPT_1_VARIANT \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg1)

# define YUNI_SCRIPT_SCRIPT_2_VARIANTS \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg1), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg2)

# define YUNI_SCRIPT_SCRIPT_3_VARIANTS \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg1), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg2), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg3)

# define YUNI_SCRIPT_SCRIPT_4_VARIANTS \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg1), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg2), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg3), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg4)


# define YUNI_SCRIPT_SCRIPT_5_VARIANTS \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg1), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg2), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg3), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg4), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg5)



# define YUNI_SCRIPT_SCRIPT_6_VARIANTS \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg1), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg2), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg3), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg4), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg5), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg6)


# define YUNI_SCRIPT_SCRIPT_7_VARIANTS \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg1), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg2), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg3), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg4), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg5), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg6), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg7)


# define YUNI_SCRIPT_SCRIPT_8_VARIANTS \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg1), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg2), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg3), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg4), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg5), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg6), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg7), \
	YUNI_SCRIPT_SCRIPT_VARIANT(arg8)


# define YUNI_SCRIPT_SCRIPT_DECLARE_CALL_WITH(...) \
	virtual bool call(Variant *retValues, const String& method, ## __VA_ARGS__)

# define YUNI_SCRIPT_SCRIPT_DECLARE_BIND_WITH(cb) \
			virtual bool bind(const String& method, cb, void *callBackData = NULL)


#endif /* !__YUNI_SCRIPT_SCRIPT_DEFINES_H__ */

