#ifdef __YUNI_SCRIPT_SCRIPT_DEFINES_H__

# undef YUNI_SCRIPT_SCRIPT_VARIANT
# undef YUNI_SCRIPT_SCRIPT_1_VARIANT
# undef YUNI_SCRIPT_SCRIPT_2_VARIANTS
# undef YUNI_SCRIPT_SCRIPT_3_VARIANTS
# undef YUNI_SCRIPT_SCRIPT_4_VARIANTS
# undef YUNI_SCRIPT_SCRIPT_5_VARIANTS
# undef YUNI_SCRIPT_SCRIPT_6_VARIANTS
# undef YUNI_SCRIPT_SCRIPT_7_VARIANTS
# undef YUNI_SCRIPT_SCRIPT_8_VARIANTS
# undef YUNI_SCRIPT_SCRIPT_DECLARE_CALL_WITH
# undef YUNI_SCRIPT_SCRIPT_DECLARE_BIND_WITH

# undef __YUNI_SCRIPT_SCRIPT_DEFINES_H__
#endif /* __YUNI_SCRIPT_SCRIPT_DEFINES_H__ */
