







#
# --- Applying the Configuation ---
#

Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "")

#
# MMX
#
IF("${YUNI_PROFILE_MMX}" STREQUAL "yes")
	IF(CMAKE_COMPILER_IS_GNUCXX)
		Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -mmmx")
	ELSE(CMAKE_COMPILER_IS_GNUCXX)
	ENDIF(CMAKE_COMPILER_IS_GNUCXX)
ENDIF("${YUNI_PROFILE_MMX}" STREQUAL "yes")

#
# 3D NOW
#
IF("${YUNI_PROFILE_3DNOW}" STREQUAL "yes")
	IF(CMAKE_COMPILER_IS_GNUCXX)
		Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -m3dnow")
	ELSE(CMAKE_COMPILER_IS_GNUCXX)
	ENDIF(CMAKE_COMPILER_IS_GNUCXX)
ENDIF("${YUNI_PROFILE_3DNOW}" STREQUAL "yes")



#
# SSE
#
IF("${YUNI_PROFILE_SSE}" STREQUAL "yes")
	IF(CMAKE_COMPILER_IS_GNUCXX)
		Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -msse -mfpmath=sse")
	ELSE(CMAKE_COMPILER_IS_GNUCXX)
		Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -msse -mfpmath=sse")
	ENDIF(CMAKE_COMPILER_IS_GNUCXX)

	# SSE2
	IF("${YUNI_PROFILE_SSE2}" STREQUAL "yes")
		IF(CMAKE_COMPILER_IS_GNUCXX)
			Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -msse2")
		ELSE(CMAKE_COMPILER_IS_GNUCXX)
			IF(MSVC)
				Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} /arch:SSE2")
			ENDIF(MSVC)
		ENDIF(CMAKE_COMPILER_IS_GNUCXX)

		# SSE3
		IF("${YUNI_PROFILE_SSE3}" STREQUAL "yes")
			IF(CMAKE_COMPILER_IS_GNUCXX)
				Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -msse3")
			ELSE(CMAKE_COMPILER_IS_GNUCXX)
			ENDIF(CMAKE_COMPILER_IS_GNUCXX)

			# SSE4
			IF("${YUNI_PROFILE_SSE4}" STREQUAL "yes")
				IF(CMAKE_COMPILER_IS_GNUCXX)
					Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -msse4")
				ELSE(CMAKE_COMPILER_IS_GNUCXX)
				ENDIF(CMAKE_COMPILER_IS_GNUCXX)
			ENDIF("${YUNI_PROFILE_SSE4}" STREQUAL "yes")

			# SSE4a
			IF("${YUNI_PROFILE_SSE4a}" STREQUAL "yes")
				IF(CMAKE_COMPILER_IS_GNUCXX)
					Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -msse4a")
				ELSE(CMAKE_COMPILER_IS_GNUCXX)
				ENDIF(CMAKE_COMPILER_IS_GNUCXX)
			ENDIF("${YUNI_PROFILE_SSE4a}" STREQUAL "yes")

			# SSE 4.1
			IF("${YUNI_PROFILE_SSE4_1}" STREQUAL "yes")
				IF(CMAKE_COMPILER_IS_GNUCXX)
					Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -msse4.1")
				ELSE(CMAKE_COMPILER_IS_GNUCXX)
				ENDIF(CMAKE_COMPILER_IS_GNUCXX)
			ENDIF("${YUNI_PROFILE_SSE4_1}" STREQUAL "yes")

			# SSE 4.2
			IF("${YUNI_PROFILE_SSE4_2}" STREQUAL "yes")
				IF(CMAKE_COMPILER_IS_GNUCXX)
					Set(YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS "${YUNI_PROFILE_CXX_FLAGS_INSTRUCTIONS_SETS} -msse4.2")
				ELSE(CMAKE_COMPILER_IS_GNUCXX)
				ENDIF(CMAKE_COMPILER_IS_GNUCXX)
			ENDIF("${YUNI_PROFILE_SSE4_2}" STREQUAL "yes")

		ENDIF("${YUNI_PROFILE_SSE3}" STREQUAL "yes")

	ENDIF("${YUNI_PROFILE_SSE2}" STREQUAL "yes")

ENDIF("${YUNI_PROFILE_SSE}" STREQUAL "yes")


