


#
# LUA
#
MACRO(DEVPACK_IMPORT_LUA)
	IF(YUNI_EXTERNAL_SCRIPT_LUA)
		IF(APPLE)
			DEVPACK_IMPORT("lua" "5.1.4" "2" "macos" "ub" "${DEVPACK_COMPILER}" "all")
		ENDIF(APPLE)
		IF(MSVC)
			DEVPACK_SMART_IMPORT("lua" "5.1.4" "1" "all")
		ENDIF(MSVC)
		IF(MINGW)
			DEVPACK_SMART_IMPORT("lua" "5.1.4" "1" "all")
		ENDIF(MINGW)

		IF(IsLinux)
			DEVPACK_SMART_IMPORT("lua" "5.1.4" "1" "all")
		ENDIF(IsLinux)
		LIST(APPEND YUNI_STATIC_SCRIPT "${YUNI_EXT_LUA_LIB}")
		LIST(APPEND YUNI_INCLUDE   "${YUNI_EXT_LUA_INCLUDE}")
		LIBYUNI_CONFIG_LIB_RAW_COMMAND("lua" "${YUNI_EXT_LUA_LIB}")
		LIBYUNI_CONFIG_INCLUDE_PATH("lua" "${YUNI_EXT_LUA_INCLUDE}")
	ENDIF(YUNI_EXTERNAL_SCRIPT_LUA)
ENDMACRO(DEVPACK_IMPORT_LUA)



#
# PThreads
#
MACRO(DEVPACK_IMPORT_PTHREADS)
	Include(FindThreads)
	If(CMAKE_USE_WIN32_THREADS_INIT)
		Message(STATUS "Threading Support: PThreads for Windows (via DevPacks)")
		IF(WIN32)
			DEVPACK_SMART_IMPORT("pthreads" "2.8.0" "3" "all")
			LIST(APPEND YUNI_STATIC_CORE "${YUNI_EXT_PTHREADS_LIB}")
			LIST(APPEND YUNI_INCLUDE   "${YUNI_EXT_PTHREADS_INCLUDE}")
			LIBYUNI_CONFIG_INCLUDE_PATH("core" "${YUNI_EXT_PTHREADS_INCLUDE}")
			LIBYUNI_CONFIG_LIB_RAW_COMMAND("core" "${YUNI_EXT_PTHREADS_LIB}")
		ENDIF(WIN32)
	Else(CMAKE_USE_WIN32_THREADS_INIT)
		IF(NOT CMAKE_USE_PTHREADS_INIT)
			MESSAGE(FATAL_ERROR "PThreads is required.")
		ENDIF(NOT CMAKE_USE_PTHREADS_INIT)
		Link_libraries(${CMAKE_THREAD_LIBS_INIT})
		LIBYUNI_CONFIG_LIB_RAW_COMMAND("core" "${CMAKE_THREAD_LIBS_INIT}")
		Message(STATUS "Threading Support: PThreads (${CMAKE_THREAD_LIBS_INIT})")
	EndIF(CMAKE_USE_WIN32_THREADS_INIT)
ENDMACRO(DEVPACK_IMPORT_PTHREADS)

