#
# YUNI_INCLUDE
#

#
# The common paths for Yuni headers
#

LIST(APPEND YUNI_INCLUDE "${PROJECT_SOURCE_DIR}/..")


IF(APPLE)
	FIND_LIBRARY(FRAMEWORK_COREFOUNDATION NAMES CoreFoundation)
	FIND_LIBRARY(FRAMEWORK_COCOA NAMES Cocoa)
	FIND_LIBRARY(FRAMEWORK_IOKIT NAMES IOKit)
ENDIF(APPLE)




#
# Core
#
IF(NOT YUNI_STATIC_CORE)
	Set(YUNI_STATIC_CORE yuni-static-core)
ELSE(NOT YUNI_STATIC_CORE)
	LIST(INSERT YUNI_STATIC_CORE 0 yuni-static-core)
ENDIF(NOT YUNI_STATIC_CORE)
# PThreads (required by `Core`)
DEVPACK_IMPORT_PTHREADS()


#
# Algorithms
#
IF(NOT YUNI_STATIC_ALGORITHMS)
	Set(YUNI_STATIC_ALGORITHMS yuni-static-algorithms)
ELSE(NOT YUNI_STATIC_ALGORITHMS)
	LIST(INSERT YUNI_STATIC_ALGORITHMS 0 yuni-static-algorithms)
ENDIF(NOT YUNI_STATIC_ALGORITHMS)


#
# Device::Display
#
IF(NOT YUNI_STATIC_DEVICE_DISPLAY)
	Set(YUNI_STATIC_CORE yuni-static-device-display)
ELSE(NOT YUNI_STATIC_DEVICE_DISPLAY)
	LIST(INSERT YUNI_STATIC_CORE 0 yuni-static-device-display)
ENDIF(NOT YUNI_STATIC_DEVICE_DISPLAY)
IF(YUNI_MODULE_DEVICE_DISPLAY)
	IF(NOT APPLE AND NOT WIN32)
		LIST(APPEND YUNI_STATIC_DEVICE_DISPLAY X11 Xrandr)
		LINK_DIRECTORIES("/usr/X11R6/lib")
	ENDIF(NOT APPLE AND NOT WIN32)

	IF(APPLE)
		LIST(APPEND YUNI_STATIC_DEVICE_DISPLAY "${FRAMEWORK_COREFOUNDATION}")
		LIST(APPEND YUNI_STATIC_DEVICE_DISPLAY "${FRAMEWORK_COCOA}")
		LIST(APPEND YUNI_STATIC_DEVICE_DISPLAY "${FRAMEWORK_IOKIT}")
	ENDIF(APPLE)

ENDIF(YUNI_MODULE_DEVICE_DISPLAY)

Set(YUNI_STATIC_NET    yuni-static-net)




IF(NOT YUNI_STATIC_GFX_CORE)
	Set(YUNI_STATIC_GFX_CORE yuni-static-gfx-core)
ELSE(NOT YUNI_STATIC_GFX_CORE)
	LIST(INSERT YUNI_STATIC_GFX_CORE 0 yuni-static-gfx-core)
ENDIF(NOT YUNI_STATIC_GFX_CORE)


Set(YUNI_STATIC_GFX3D  yuni-static-gfx-core yuni-static-gfx3d-core "${YUNI_STATIC_DEVICE_DISPLAY}")

Set(YUNI_STATIC_SCRIPT yuni-static-script)




#
# Module Gfx3D
#
IF(YUNI_MODULE_GFX3D)
	# Irrlicht
	IF(YUNI_EXTERNAL_3D_IRRLICHT)
		DEVPACK_IMPORT_IRRLICHT()
		LIST(INSERT YUNI_STATIC_GFX3D 0 yuni-static-gfx3d-irrlicht)
	ENDIF(YUNI_EXTERNAL_3D_IRRLICHT)

	# Ogre 3D
	IF(YUNI_EXTERNAL_3D_OGRE)
		DEVPACK_IMPORT_OGRE()
		LIST(INSERT YUNI_STATIC_GFX3D 0 yuni-static-gfx3d-ogre)
	ENDIF(YUNI_EXTERNAL_3D_OGRE)
ENDIF(YUNI_MODULE_GFX3D)

#
# Script
#
IF(YUNI_MODULE_SCRIPT)

	#
	# Lua
	#
	IF(YUNI_EXTERNAL_SCRIPT_LUA)
		DEVPACK_IMPORT_LUA()
	ENDIF(YUNI_EXTERNAL_SCRIPT_LUA)

ENDIF(YUNI_MODULE_SCRIPT)

