

IF(LIBYUNI_CONFIG_ENABLED)
	IF(MSVC90)
		Set(YUNI_LIBYUNI_CONFIG_COMPILER "vs9")
	ELSE(MSVC90)
		IF(MINGW)
			Set(YUNI_LIBYUNI_CONFIG_COMPILER "mingw")
		ELSE(MINGW)
			Set(YUNI_LIBYUNI_CONFIG_COMPILER "gcc")
		ENDIF(MINGW)
	ENDIF(MSVC90)

	Set(YUNI_LIBYUNI_CONFIG_TARGET_INIFILE
		"${CMAKE_CURRENT_SOURCE_DIR}/yuni.config.${YUNI_LIBYUNI_CONFIG_COMPILER}")
	FILE(WRITE "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "[settings]\n")

ENDIF(LIBYUNI_CONFIG_ENABLED)


MACRO(LIBYUNI_CONFIG_CFLAG module pth)
	IF(LIBYUNI_CONFIG_ENABLED)
		FILE(APPEND "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "cxxflag:${module} = ${pth}\n")
	ENDIF(LIBYUNI_CONFIG_ENABLED)
ENDMACRO(LIBYUNI_CONFIG_CFLAG)


MACRO(LIBYUNI_CONFIG_LIB module pth)
	IF(LIBYUNI_CONFIG_ENABLED)
		FILE(APPEND "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "lib:${module} = ${pth}\n")
	ENDIF(LIBYUNI_CONFIG_ENABLED)
ENDMACRO(LIBYUNI_CONFIG_LIB)

MACRO(LIBYUNI_CONFIG_LIB_RAW_COMMAND module pth)
	IF(LIBYUNI_CONFIG_ENABLED)
		FILE(APPEND "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "lib,rawcommand:${module} = ${pth}\n")
	ENDIF(LIBYUNI_CONFIG_ENABLED)
ENDMACRO(LIBYUNI_CONFIG_LIB_RAW_COMMAND)

MACRO(LIBYUNI_CONFIG_FRAMEWORK module pth)
	IF(LIBYUNI_CONFIG_ENABLED)
		FILE(APPEND "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "framework:${module} = ${pth}\n")
	ENDIF(LIBYUNI_CONFIG_ENABLED)
ENDMACRO(LIBYUNI_CONFIG_FRAMEWORK)



MACRO(LIBYUNI_CONFIG_DEFINITION module pth)
	IF(LIBYUNI_CONFIG_ENABLED)
		FILE(APPEND "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "define:${module} = ${pth}\n")
	ENDIF(LIBYUNI_CONFIG_ENABLED)
ENDMACRO(LIBYUNI_CONFIG_DEFINITION)

MACRO(LIBYUNI_CONFIG_DEPENDENCY module pth)
	IF(LIBYUNI_CONFIG_ENABLED)
		FILE(APPEND "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "dependency:${module} = ${pth}\n")
	ENDIF(LIBYUNI_CONFIG_ENABLED)
ENDMACRO(LIBYUNI_CONFIG_DEPENDENCY)




MACRO(LIBYUNI_CONFIG_INCLUDE_PATH module pth)
	IF(LIBYUNI_CONFIG_ENABLED)
		FILE(APPEND "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "path.include:${module} = ${pth}\n")
	ENDIF(LIBYUNI_CONFIG_ENABLED)
ENDMACRO(LIBYUNI_CONFIG_INCLUDE_PATH)

MACRO(LIBYUNI_CONFIG_LIB_PATH module pth)
	IF(LIBYUNI_CONFIG_ENABLED)
		FILE(APPEND "${YUNI_LIBYUNI_CONFIG_TARGET_INIFILE}" "path.lib:${module} = ${pth}\n")
	ENDIF(LIBYUNI_CONFIG_ENABLED)
ENDMACRO(LIBYUNI_CONFIG_LIB_PATH)

