
STRING(COMPARE EQUAL "${CMAKE_BUILD_TYPE}" "" NO_BUILD_TYPE)
IF(NO_BUILD_TYPE)
	SET(CMAKE_BUILD_TYPE "debug")
ELSE(NO_BUILD_TYPE)
	STRING(COMPARE EQUAL "${CMAKE_BUILD_TYPE}" "debug"   BUILD_TYPE_IS_DEBUG)
	STRING(COMPARE EQUAL "${CMAKE_BUILD_TYPE}" "release" BUILD_TYPE_IS_RELEASE)
	IF(NOT BUILD_TYPE_IS_DEBUG AND NOT BUILD_TYPE_IS_RELEASE)
		SET(CMAKE_BUILD_TYPE "debug")
	ENDIF(NOT BUILD_TYPE_IS_DEBUG AND NOT BUILD_TYPE_IS_RELEASE)
ENDIF(NO_BUILD_TYPE)
SET(YUNI_TARGET "${CMAKE_BUILD_TYPE}")


