
SET(YUNI_TARGET_DEBUG   true)
SET(YUNI_TARGET_RELEASE true)


STRING(COMPARE EQUAL "${CMAKE_BUILD_TYPE}" "" NO_BUILD_TYPE)
IF(NO_BUILD_TYPE)
	STRING(COMPARE EQUAL "${TARGET}" "" NO_BUILD_TYPE)
	IF(NO_BUILD_TYPE)
		STRING(COMPARE EQUAL "${YUNI_TARGET}" "" NO_BUILD_TYPE)
		IF(NO_BUILD_TYPE)
			SET(CMAKE_BUILD_TYPE "debug")
		ELSE(NO_BUILD_TYPE)
			SET(CMAKE_BUILD_TYPE "${YUNI_TARGET}")
		ENDIF(NO_BUILD_TYPE)
	ELSE(NO_BUILD_TYPE)
		SET(CMAKE_BUILD_TYPE "${TARGET}")
	ENDIF(NO_BUILD_TYPE)
ENDIF(NO_BUILD_TYPE)

STRING(COMPARE EQUAL "${CMAKE_BUILD_TYPE}" "debug"   BUILD_TYPE_IS_DEBUG)
STRING(COMPARE EQUAL "${CMAKE_BUILD_TYPE}" "release" BUILD_TYPE_IS_RELEASE)
IF(NOT BUILD_TYPE_IS_DEBUG AND NOT BUILD_TYPE_IS_RELEASE)
	SET(CMAKE_BUILD_TYPE "debug")
ENDIF(NOT BUILD_TYPE_IS_DEBUG AND NOT BUILD_TYPE_IS_RELEASE)


STRING(COMPARE EQUAL "${CMAKE_BUILD_TYPE}" "debug"   BUILD_TYPE_IS_DEBUG)
STRING(COMPARE EQUAL "${CMAKE_BUILD_TYPE}" "release" BUILD_TYPE_IS_RELEASE)
IF(BUILD_TYPE_IS_DEBUG)
	SET(YUNI_TARGET_DEBUG  true)
ENDIF(BUILD_TYPE_IS_DEBUG)
IF(BUILD_TYPE_IS_RELEASE)
	SET(YUNI_TARGET_RELEASE  true)
ENDIF(BUILD_TYPE_IS_RELEASE)

# Reset
SET(YUNI_TARGET "${CMAKE_BUILD_TYPE}")
SET(TARGET "${CMAKE_BUILD_TYPE}")

