
CC = gcc

CXX = g++

CFLAGS = -Wall -W -ansi -ggdb -I../../src/

CXXFLAGS = -Wall -W -std=gnu++0x -ggdb -I../../src/

LDFLAGS = -L../../src/build/debug/lib -l"yuni-static-core"

SRC = main.cpp parser/parser.cpp ast/type.cpp

OBJ = $(SRC:.cpp=.o)

NAME = nanyc


all: $(NAME)

$(NAME): $(OBJ) parser/engine.o
	$(CXX) $(CXXFLAGS) $(OBJ) parser/engine.o $(LDFLAGS) -o $(NAME)

clean:
	rm -f *~ \#*
	rm -f *.o
	rm -f parser/*.o

distclean: clean
	rm -f $(NAME)
