
CC = gcc

CXX = g++

CFLAGS = -Wall -W -ansi -ggdb -I../../src/

CXXFLAGS = -Wall -W -ggdb -I../../src/

SRC = main.cpp parser/parser.cpp

OBJ = $(SRC:.cpp=.o)

NAME = nanyc.exe


all: $(NAME)

$(NAME): $(OBJ) parser/engine.o
	$(CXX) $(CXXFLAGS) $(OBJ) parser/engine.o -o $(NAME)

clean:
	del /Q *~
	del /Q *.o
	del /Q parser\*.o

distclean: clean
	del /Q $(NAME)
