
CC = gcc

CXX = g++

CFLAGS = -Wall -W -Wextra -ggdb -I../../src/

CXXFLAGS = -Wall -W -Wextra -std=gnu++0x -ggdb -I../../src/

LDFLAGS = -L../../src/build/debug/lib -l"yuni-static-core"

SRC = main.cpp parser/parser.cpp ast/type.cpp

OBJ = $(SRC:.cpp=.o)

NAME = nanyc.exe


all: $(NAME)

$(NAME): $(OBJ) parser/engine.o
	$(CXX) $(CXXFLAGS) $(OBJ) parser/engine.o $(LDFLAGS) -o $(NAME)

clean:
	del /Q *~
	del /Q *.o
	del /Q parser\*.o

distclean: clean
	del /Q $(NAME)
