

namespace // anonymous
{

	template<class StringT>
	static void PrepareWebPageHtml(StringT& out)
	{
		out.clear()
			<< "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
			<< "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n"
			<< "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"fr\" lang=\"fr\">\n"
			<< "<head>\n"
			<< "<meta http-equiv=\"Content-Type\" content=\"application/xhtml+xml; charset=utf-8\" />\n"
			<< "<meta name=\"language\" content=\"en\" />\n"
			<< "<title>@{TITLE}</title>\n"
			<< "<meta name=\"copyright\" content=\"libyuni.org 2011\" />\n"
			<< "<meta name=\"rating\" content=\"general\" />\n"
			<< "<meta name=\"author\" content=\"libyuni.org\" />\n"
			<< "<meta name=\"description\" content=\"@{DESCRIPTION}\" />\n"
			<< "<meta name=\"keywords\" content=\"@{KEYWORDS}\" />\n"
			<< "<meta name=\"viewport\" content=\"width=1024\" />\n"
			<< "<meta name=\"DC.Title\" content=\"@{TITLE}\" />\n"
			<< "<meta name=\"DC.Creator\" content=\"libyuni.org\" />\n"
			<< "<meta name=\"DC.Description\" content=\"@{DESCRIPTION}\" />\n"
			<< "<meta name=\"DC.Type\" content=\"text\" />\n"
			<< "<meta name=\"DC.Format\" content=\"text/html\" />\n"
			<< "<meta http-equiv='pragma' content='public' />\n"
			<< "<link rel=\"icon\"  href=\"favicon.ico\" type=\"image/x-icon\" />\n"
			<< "<link rel='stylesheet' type='text/css' media='all' href=\"@{ROOT}/theme/default/css/yuni.css\" />\n"
			<< "<link rel='stylesheet' type='text/css' media='print' href=\"@{ROOT}/theme/default/css/yuni-print.css\" />\n"
			<< "<script type=\"text/javascript\" src=\"@{ROOT}/theme/default/sh/shCore.js\"></script>\n"
			<< "<script type=\"text/javascript\" src=\"@{ROOT}/theme/default/sh/shBrushCpp.js\"></script>\n"
			<< "<link type=\"text/css\" rel=\"stylesheet\" href=\"@{ROOT}/theme/default/sh/shCoreDefault.css\" />\n"
			<< "<link type=\"text/css\" rel=\"Stylesheet\" href=\"@{ROOT}/theme/default/sh/shThemeEclipse.css\" />\n"
			<< "<link rel=\"stylesheet\" href=\"@{ROOT}/theme/default/breadcrumb/styles/BreadCrumb.css\" type=\"text/css\">\n"
			<< "<script type=\"text/javascript\" src=\"@{ROOT}/theme/default/breadcrumb/js/jquery.js\"></script>\n"
			<< "<script src=\"@{ROOT}/theme/default/breadcrumb/js/jquery.easing.1.3.js\" type=\"text/javascript\" language=\"JavaScript\"></script>\n"
			<< "<script src=\"@{ROOT}/theme/default/breadcrumb/js/jquery.jBreadCrumb.1.1.js\" type=\"text/javascript\" language=\"JavaScript\"></script>\n"
			<< "</head>\n"
			<< "<body>\n"
			<< "<!--\n"
			<< "title : @{TITLE}\n"
			<< "source : @{URL}\n"
			<< "-->\n"
			<< "<script type=\"text/javascript\">\n"
			<< "<!--\n"
			<< "function toggle_toc() {\n"
			<< "	var e = document.getElementById('toclist');\n"
			<< "	var l = document.getElementById('toclink');\n"
			<< "	if (e && l) {\n"
			<< "		if (e.style.display == 'block') {\n"
			<< "			e.style.display = 'none';\n"
			<< "			l.innerHTML = \"[ Show ]\";\n"
			<< "		} else {\n"
			<< "			e.style.display = 'block';\n"
			<< "			l.innerHTML = \"[ Hide ]\";\n"
			<< "		}\n"
			<< "	}\n"
			<< "}\n"
			<< "//-->\n"
			<< "</script>\n"
			<< "<table class=\"layout\">\n"
			<< "<tr>\n"
			<< "<td class=\"leftspace\"></td>\n"
			<< "<td class=\"logo\"><img src=\"@{ROOT}/theme/default/images/logo.png\" alt=\"Yuni Logo\" /></td>\n"
			<< "<td class=\"title\"><span class=\"unbreakable\"><strong>Yuni </strong>Framework</span>\n"
			<< "<div class=\"breadCrumbHolder module\">\n"
			<< "<div id=\"breadCrumb0\" class=\"breadCrumb module\">\n"
			<< "<ul>\n"
			<< "<li><a href=\"@{ROOT}/@{INDEX}\">Home</a></li>\n"
			<< "@{URL_PARTS}\n"
			<< "</ul>\n"
			<< "</div>\n"
			<< "</div>\n"
			<< "</td>\n"
			<< "<td class=\"links\">\n"
			<< "<div id=\"mainmenu\"><input type=\"text\"/></div>\n"
			<< "</td>\n"
			<< "<td class=\"space\"></td>\n"
			<< "</tr>\n"
			<< "<!-- space -->\n"
			<< "<tr>\n"
			<< "<td></td><td></td><td class=\"vspace\"></td><td></td>\n"
			<< "</tr>\n"
			<< "<tr>\n"
			<< "<td colspan=\"2\" class=\"leftmenu\">\n"
			<< "<div>\n"
			<< "@{QUICKLINKS_BEGIN}\n"
			<< "<fieldset><legend>&nbsp;Quick links&nbsp;</legend>\n"
			<< "	<a href=\"@{ROOT}/en/documentation/@{INDEX}\">Documentation</a>\n"
			<< "	<a href=\"@{ROOT}/en/downloads/@{INDEX}\">Download</a>\n"
			<< "	<a href=\"@{ROOT}/en/developers/@{INDEX}\">Developers</a>\n"
			<< "	<a href=\"@{ROOT}/en/links/@{INDEX}\">Links</a>\n"
			<< "	<a href=\"@{ROOT}/en/contacts/@{INDEX}\">Contacts</a>\n"
			<< "</fieldset>\n"
			<< "@{QUICKLINKS_END}\n"
			<< "<!--\n"
			<< "<fieldset><legend>&nbsp;Page&nbsp;</legend>\n"
			<< "	<a href=\"#\">View history</a>\n"
			<< "</fieldset>\n"
			<< "-->\n"
			<< "@{TAGFIELD_BEGIN}\n"
			<< "<fieldset><legend>&nbsp;@{TAGFIELD_COUNT}&nbsp;</legend>\n"
			<< "	<a href=\"#\">documentation <span>(234)</span></a>\n"
			<< "	<a href=\"#\">threading <span>(12)</span></a>\n"
			<< "	<a href=\"#\">ownership <span>(8)</span></a>\n"
			<< "	<a href=\"#\">policy <span>(5)</span></a>\n"
			<< "</fieldset>\n"
			<< "@{TAGFIELD_END}\n"
			<< "</div>\n"
			<< "</td>\n"
			<< "<td class=\"laycontent\" colspan=\"2\">\n"
			<< "@{TOC_BEGIN}\n"
			<< "<div id=\"toc\" class=\"toc\">\n"
			<< "<div>\n"
			<< "<span><b>&nbsp;TOC</b> <a id=\"toclink\" href=\"javascript:toggle_toc()\">[ Hide ]</a></span>\n"
			<< "<div id=\"toclist\" style=\"display:block\">\n"
			<< "<ol>\n"
			<< "	<li><a href=\"#\">Ownership</a>\n"
			<< "	<ol>\n"
			<< "		<li><a href=\"#\">Reference counted (thread safe)</a></li>\n"
			<< "		<li><a href=\"#\">Reference counted (not thread safe)</a></li>\n"
			<< "	</ol>\n"
			<< "	</li>\n"
			<< "	<li><a href=\"#\">Ownership</a>\n"
			<< "	<ol>\n"
			<< "		<li><a href=\"#\">Reference counted (thread safe)</a></li>\n"
			<< "		<li><a href=\"#\">Reference counted (not thread safe)</a></li>\n"
			<< "	</ol>\n"
			<< "	</li>\n"
			<< "	<li><a href=\"#\">Ownership</a>\n"
			<< "	<ol>\n"
			<< "		<li><a href=\"#\">Reference counted (thread safe)</a></li>\n"
			<< "		<li><a href=\"#\">Reference counted (not thread safe)</a></li>\n"
			<< "	</ol>\n"
			<< "	</li>\n"
			<< "</ol>\n"
			<< "</div>\n"
			<< "</div>\n"
			<< "</div>\n"
			<< "@{TOC_END}\n"
			<< "<h1>@{TITLE}</h1>\n"
			<< "<div class=\"content\">\n"
			<< "@{CONTENT}\n"
			<< "@{DIRECTORY_INDEX}\n"
			<< "</div> <!-- content -->\n"
			<< "<div class=\"modified\">\n"
			<< "Last modified : September 11, 2011\n"
			<< "</div>\n"
			<< "</td>\n"
			<< "<td></td>\n"
			<< "</tr>\n"
			<< "</table>\n"
			<< "<table class=\"footer\">\n"
			<< "<tr>\n"
			<< "<td style=\"width:240px;min-width:240px\"></td>\n"
			<< "<td class=\"footerlink right\">sitemap</td>\n"
			<< "<td class=\"footerlink\">\n"
			<< "<a href=\"@{ROOT}/en/documentation/@{INDEX}\">Documentation</a>\n"
			<< "<a href=\"@{ROOT}/en/downloads/@{INDEX}\">Downloads</a>\n"
			<< "<a href=\"@{ROOT}/en/links/@{INDEX}\">Links</a>\n"
			<< "<a href=\"@{ROOT}/en/contacts/@{INDEX}\">Contacts</a>\n"
			<< "<a href=\"@{ROOT}/en/sitemap/@{INDEX}\">Sitemap</a>\n"
			<< "</td>\n"
			<< "<td class=\"footerlink right\">Documentation</td>\n"
			<< "<td class=\"footerlink\">\n"
			<< "<a href=\"@{ROOT}/en/documentation/v0.2/user/@{INDEX}\">User's manual (v0.2)</a>\n"
			<< "<a href=\"@{ROOT}/en/documentation/v0.2/doxygen/@{INDEX}\">Doxygen (v0.2)</a>\n"
			<< "<a href=\"@{ROOT}/en/documentation/trunk/user/@{INDEX}\">User's manual (trunk)</a>\n"
			<< "<a href=\"@{ROOT}/en/documentation/trunk/doxygen/@{INDEX}\">Doxygen (trunk)</a>\n"
			<< "</td>\n"
			<< "<td></td>\n"
			<< "</tr>\n"
			<< "</table>\n"
			<< "</div>\n"
			<< "<script type=\"text/javascript\">\n"
			<< "jQuery.fn.jBreadCrumb.defaults.easing = 'linear';\n"
			<< "jQuery(document).ready(function()\n"
			<< "{\n"
			<< "	jQuery(\"#breadCrumb0\").jBreadCrumb();\n"
			<< "})\n"
			<< "</script>\n"
			<< "<script type=\"text/javascript\">SyntaxHighlighter.all();</script>\n"
			<< "</body>\n"
			<< "</html>\n"
			;
	}



} // anonymous namespace


