

namespace // anonymous
{

	template<class StringT>
	static void PrepareWebPageHtml(StringT& out)
	{
		out.clear()
			<< "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
			<< "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n"
			<< "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"fr\" lang=\"fr\">\n"
			<< "<head>\n"
			<< "<meta http-equiv=\"Content-Type\" content=\"application/xhtml+xml; charset=utf-8\" />\n"
			<< "<meta name=\"language\" content=\"en\" />\n"
			<< "<title>@{TITLE}</title>\n"
			<< "<meta name=\"copyright\" content=\"libyuni.org 2011\" />\n"
			<< "<meta name=\"rating\" content=\"general\" />\n"
			<< "<meta name=\"author\" content=\"libyuni.org\" />\n"
			<< "<meta name=\"description\" content=\"@{DESCRIPTION}\" />\n"
			<< "<meta name=\"keywords\" content=\"@{KEYWORDS}\" />\n"
			<< "<meta name=\"viewport\" content=\"width=1024\" />\n"
			<< "<meta name=\"DC.Title\" content=\"@{TITLE}\" />\n"
			<< "<meta name=\"DC.Creator\" content=\"libyuni.org\" />\n"
			<< "<meta name=\"DC.Description\" content=\"@{DESCRIPTION}\" />\n"
			<< "<meta name=\"DC.Type\" content=\"text\" />\n"
			<< "<meta name=\"DC.Format\" content=\"text/html\" />\n"
			<< "<meta http-equiv='pragma' content='public' />\n"
			<< "<link rel=\"icon\"  href=\"favicon.ico\" type=\"image/x-icon\" />\n"
			<< "<link rel='stylesheet' type='text/css' media='all' href=\"@{ROOT}/theme/default/css/yuni.css\" />\n"
			<< "<link rel='stylesheet' type='text/css' media='print' href=\"@{ROOT}/theme/default/css/yuni-print.css\" />\n"
			<< "<script type=\"text/javascript\" src=\"@{ROOT}/theme/default/sh/shCore.js\"></script>\n"
			<< "<script type=\"text/javascript\" src=\"@{ROOT}/theme/default/sh/shBrushCpp.js\"></script>\n"
			<< "<link type=\"text/css\" rel=\"stylesheet\" href=\"@{ROOT}/theme/default/sh/shCoreDefault.css\" />\n"
			<< "<link type=\"text/css\" rel=\"Stylesheet\" href=\"@{ROOT}/theme/default/sh/shThemeEclipse.css\" />\n"
			<< "<link rel=\"stylesheet\" href=\"@{ROOT}/theme/default/breadcrumb/styles/BreadCrumb.css\" type=\"text/css\">\n"
			<< "<script type=\"text/javascript\" src=\"@{ROOT}/theme/default/breadcrumb/js/jquery.js\"></script>\n"
			<< "<script src=\"@{ROOT}/theme/default/breadcrumb/js/jquery.easing.1.3.js\" type=\"text/javascript\" language=\"JavaScript\"></script>\n"
			<< "<script src=\"@{ROOT}/theme/default/breadcrumb/js/jquery.jBreadCrumb.1.1.js\" type=\"text/javascript\" language=\"JavaScript\"></script>\n"
			<< "</head>\n"
			<< "<body>\n"
			<< "<!--\n"
			<< "title : @{TITLE}\n"
			<< "source : @{URL}\n"
			<< "-->\n"
			<< "<script type=\"text/javascript\">\n"
			<< "<!--\n"
			<< "function toggle_toc() {\n"
			<< "	var e = document.getElementById('toclist');\n"
			<< "	var l = document.getElementById('toclink');\n"
			<< "	if (e && l) {\n"
			<< "		if (e.style.display == 'block') {\n"
			<< "			e.style.display = 'none';\n"
			<< "			l.innerHTML = \"[ Show ]\";\n"
			<< "		} else {\n"
			<< "			e.style.display = 'block';\n"
			<< "			l.innerHTML = \"[ Hide ]\";\n"
			<< "		}\n"
			<< "	}\n"
			<< "}\n"
			<< "//-->\n"
			<< "</script>\n"
			<< "<table class=\"layout\">\n"
			<< "<tr>\n"
			<< "<td class=\"leftspace\"></td>\n"
			<< "<td class=\"logo\"><img src=\"@{ROOT}/theme/default/images/logo.png\" alt=\"Yuni Logo\" /></td>\n"
			<< "<td class=\"title\"><span class=\"unbreakable\"><strong>Yuni </strong>Framework</span>\n"
			<< "<div class=\"breadCrumbHolder module\">\n"
			<< "<div id=\"breadCrumb0\" class=\"breadCrumb module\">\n"
			<< "<ul>\n"
			<< "<li><a href=\"@{ROOT}\">Home</a></li>\n"
			<< "@{URL_PARTS}\n"
			<< "</ul>\n"
			<< "</div>\n"
			<< "</div>\n"
			<< "</td>\n"
			<< "<td class=\"links\">\n"
			<< "<div id=\"mainmenu\"><input type=\"text\"/></div>\n"
			<< "</td>\n"
			<< "<td class=\"space\"></td>\n"
			<< "</tr>\n"
			<< "<!-- space -->\n"
			<< "<tr>\n"
			<< "<td></td><td></td><td class=\"vspace\"></td><td></td>\n"
			<< "</tr>\n"
			<< "<tr>\n"
			<< "<td colspan=\"2\" class=\"leftmenu\">\n"
			<< "<div>\n"
			<< "@{QUICKLINKS_BEGIN}\n"
			<< "<fieldset><legend>&nbsp;Quick links&nbsp;</legend>\n"
			<< "	<a href=\"@{ROOT}/en/documentation\">Documentation</a>\n"
			<< "	<a href=\"@{ROOT}/en/downloads\">Download</a>\n"
			<< "	<a href=\"@{ROOT}/en/developers\">Developers</a>\n"
			<< "	<a href=\"@{ROOT}/en/links\">Links</a>\n"
			<< "	<a href=\"@{ROOT}/en/contacts\">Contacts</a>\n"
			<< "</fieldset>\n"
			<< "@{QUICKLINKS_END}\n"
			<< "<!--\n"
			<< "<fieldset><legend>&nbsp;Page&nbsp;</legend>\n"
			<< "	<a href=\"#\">View history</a>\n"
			<< "</fieldset>\n"
			<< "-->\n"
			<< "@{TAGFIELD_BEGIN}\n"
			<< "<fieldset><legend>&nbsp;@{TAGFIELD_COUNT}&nbsp;</legend>\n"
			<< "	<a href=\"#\">documentation <span>(234)</span></a>\n"
			<< "	<a href=\"#\">threading <span>(12)</span></a>\n"
			<< "	<a href=\"#\">ownership <span>(8)</span></a>\n"
			<< "	<a href=\"#\">policy <span>(5)</span></a>\n"
			<< "</fieldset>\n"
			<< "@{TAGFIELD_END}\n"
			<< "</div>\n"
			<< "</td>\n"
			<< "<td class=\"laycontent\" colspan=\"2\">\n"
			<< "@{TOC_BEGIN}\n"
			<< "<div id=\"toc\" class=\"toc\">\n"
			<< "<div>\n"
			<< "<span><b>&nbsp;TOC</b> <a id=\"toclink\" href=\"javascript:toggle_toc()\">[ Hide ]</a></span>\n"
			<< "<div id=\"toclist\" style=\"display:block\">\n"
			<< "<ol>\n"
			<< "	<li><a href=\"#\">Ownership</a>\n"
			<< "	<ol>\n"
			<< "		<li><a href=\"#\">Reference counted (thread safe)</a></li>\n"
			<< "		<li><a href=\"#\">Reference counted (not thread safe)</a></li>\n"
			<< "	</ol>\n"
			<< "	</li>\n"
			<< "	<li><a href=\"#\">Ownership</a>\n"
			<< "	<ol>\n"
			<< "		<li><a href=\"#\">Reference counted (thread safe)</a></li>\n"
			<< "		<li><a href=\"#\">Reference counted (not thread safe)</a></li>\n"
			<< "	</ol>\n"
			<< "	</li>\n"
			<< "	<li><a href=\"#\">Ownership</a>\n"
			<< "	<ol>\n"
			<< "		<li><a href=\"#\">Reference counted (thread safe)</a></li>\n"
			<< "		<li><a href=\"#\">Reference counted (not thread safe)</a></li>\n"
			<< "	</ol>\n"
			<< "	</li>\n"
			<< "</ol>\n"
			<< "</div>\n"
			<< "</div>\n"
			<< "</div>\n"
			<< "@{TOC_END}\n"
			<< "<h1>@{TITLE}</h1>\n"
			<< "<div class=\"content\">\n"
			<< "<!--\n"
			<< "<h1>1. Ownership</h1>\n"
			<< "<h2>1.1. Reference counted (thread-safe)</h2>\n"
			<< "<p>\n"
			<< "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique, purus ac condimentum mollis, massa metus vehicula mauris, sed iaculis libero ipsum sit amet turpis. Quisque tincidunt adipiscing ante sed faucibus. Nulla quis lacus id nunc ullamcorper porta non eget ante. Phasellus elementum facilisis eros, at commodo augue imperdiet vel. Donec ac eros luctus nunc accumsan pretium. In quis lacus ipsum. Pellentesque et nibh nec metus tristique pellentesque et eu arcu. Morbi sed posuere urna. Maecenas bibendum ullamcorper nisl, eu convallis urna sollicitudin at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum eget scelerisque ante. Nulla sed eros id nulla tempor dignissim. Nam id nisl eu sem condimentum vestibulum. Suspendisse ligula massa, imperdiet id varius at, dignissim ut enim.\n"
			<< "</p>\n"
			<< "<p>\n"
			<< "Nulla porta quam ac velit vestibulum non congue sapien imperdiet. Aenean eros neque, bibendum eu faucibus ac, molestie vel mi. In auctor mi eget magna ullamcorper rhoncus. Vestibulum non purus at lorem pretium semper ut vitae ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam ac lectus eu lorem cursus egestas. Sed commodo ipsum sit amet turpis venenatis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam elementum tristique imperdiet. Donec convallis velit non turpis blandit lacinia. Donec hendrerit interdum lacus ut ultricies. Nullam ut iaculis purus. Aenean sollicitudin lobortis sem quis elementum. Praesent pulvinar varius est, et aliquam tortor egestas vel. Mauris quis mauris risus, sit amet consequat justo. Aliquam quis eros quis lorem sagittis ultricies. Sed eros felis, iaculis a vulputate sed, gravida vel neque. Nulla scelerisque, nulla at vestibulum iaculis, nunc nulla porta erat, eu tincidunt neque justo a lectus.\n"
			<< "</p>\n"
			<< "<p>\n"
			<< "Aenean mattis, nunc vitae mattis pretium, risus erat vulputate metus, vitae accumsan libero nisl eget lacus. Nulla est libero, vulputate nec scelerisque sed, aliquet non diam. Duis ut rhoncus arcu. Phasellus fermentum volutpat lacus eu cursus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Integer nibh felis, egestas ut aliquam non, aliquam id mi. Morbi laoreet mauris vitae ante accumsan eu vestibulum tellus vestibulum. Duis pulvinar vulputate tempor. Aenean eleifend diam eget diam ultrices tempor. Mauris eu tellus felis, sit amet gravida risus.\n"
			<< "</p>\n"
			<< "<table>\n"
			<< "<tr>\n"
			<< "<th>RAW Type</th>\n"
			<< "<th>Pikoli</th>\n"
			<< "<th>Pikoli</th>\n"
			<< "</tr>\n"
			<< "<tr>\n"
			<< "<td>Somewhere in the table</td>\n"
			<< "<td>nyu</td>\n"
			<< "<td>nyu</td>\n"
			<< "</tr>\n"
			<< "<tr>\n"
			<< "<td>Somewhere in the table !!! Mouarf</td>\n"
			<< "<td>nyu</td>\n"
			<< "<td>nyu</td>\n"
			<< "</tr>\n"
			<< "</table>\n"
			<< "<p>\n"
			<< "Fusce mattis, nisl non dignissim egestas, justo nibh rhoncus orci, quis scelerisque augue leo et odio. Nulla at odio nisl, et commodo est. Nulla placerat rutrum tincidunt. Sed sodales luctus nibh, sed pellentesque erat placerat in. Sed pulvinar massa at ipsum rutrum luctus ultricies erat consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ultricies scelerisque diam, sed pretium elit facilisis in. Curabitur eget lorem sed mi dictum porta viverra id arcu. Nulla rutrum, turpis in vulputate cursus, ipsum ligula feugiat odio, vel hendrerit dui nulla nec arcu. Curabitur id leo elit, ac molestie ipsum.\n"
			<< "</p>\n"
			<< "<h2>1.2. Reference counted (not thread-safe)</h2>\n"
			<< "<p>\n"
			<< "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique, purus ac condimentum mollis, massa metus vehicula mauris, sed iaculis libero ipsum sit amet turpis. Quisque tincidunt adipiscing ante sed faucibus. Nulla quis lacus id nunc ullamcorper porta non eget ante. Phasellus elementum facilisis eros, at commodo augue imperdiet vel. Donec ac eros luctus nunc accumsan pretium. In quis lacus ipsum. Pellentesque et nibh nec metus tristique pellentesque et eu arcu. Morbi sed posuere urna. Maecenas bibendum ullamcorper nisl, eu convallis urna sollicitudin at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum eget scelerisque ante. Nulla sed eros id nulla tempor dignissim. Nam id nisl eu sem condimentum vestibulum. Suspendisse ligula massa, imperdiet id varius at, dignissim ut enim.\n"
			<< "</p>\n"
			<< "<h1>2. Dynamic casting</h1>\n"
			<< "<h2>2.1. Reference counted (thread-safe)</h2>\n"
			<< "<p>\n"
			<< "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique, purus ac condimentum mollis, massa metus vehicula mauris, sed iaculis libero ipsum sit amet turpis. Quisque tincidunt adipiscing ante sed faucibus. Nulla quis lacus id nunc ullamcorper porta non eget ante. Phasellus elementum facilisis eros, at commodo augue imperdiet vel. Donec ac eros luctus nunc accumsan pretium. In quis lacus ipsum. Pellentesque et nibh nec metus tristique pellentesque et eu arcu. Morbi sed posuere urna. Maecenas bibendum ullamcorper nisl, eu convallis urna sollicitudin at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum eget scelerisque ante. Nulla sed eros id nulla tempor dignissim. Nam id nisl eu sem condimentum vestibulum. Suspendisse ligula massa, imperdiet id varius at, dignissim ut enim.\n"
			<< "</p>\n"
			<< "<p>\n"
			<< "Nulla porta quam ac velit vestibulum non congue sapien imperdiet. Aenean eros neque, bibendum eu faucibus ac, molestie vel mi. In auctor mi eget magna ullamcorper rhoncus. Vestibulum non purus at lorem pretium semper ut vitae ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam ac lectus eu lorem cursus egestas. Sed commodo ipsum sit amet turpis venenatis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam elementum tristique imperdiet. Donec <a href=\"#\">convallis velit non turpis</a> blandit lacinia. Donec hendrerit interdum lacus ut ultricies. Nullam ut iaculis purus. Aenean sollicitudin lobortis sem quis elementum. Praesent pulvinar varius est, et aliquam tortor egestas vel. Mauris quis mauris risus, sit amet consequat justo. Aliquam quis eros quis lorem sagittis ultricies. Sed eros felis, iaculis a vulputate sed, gravida vel neque. Nulla scelerisque, nulla at vestibulum iaculis, nunc nulla porta erat, eu tincidunt neque justo a lectus.\n"
			<< "</p>\n"
			<< "<p>\n"
			<< "Aenean mattis, nunc vitae mattis pretium, risus erat vulputate metus, vitae accumsan libero nisl eget lacus. Nulla est libero, vulputate nec scelerisque sed, aliquet non diam. Duis ut rhoncus arcu. Phasellus fermentum volutpat lacus eu cursus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Integer nibh felis, egestas ut aliquam non, aliquam id mi. Morbi laoreet mauris vitae ante accumsan eu vestibulum tellus vestibulum. Duis pulvinar vulputate tempor. Aenean eleifend diam eget diam ultrices tempor. Mauris eu tellus felis, sit amet gravida risus.\n"
			<< "</p>\n"
			<< "<p>\n"
			<< "Fusce mattis, nisl non dignissim egestas, justo nibh rhoncus orci, quis scelerisque augue leo et odio. Nulla at odio nisl, et commodo est. Nulla placerat rutrum tincidunt. Sed sodales luctus nibh, sed pellentesque erat placerat in. Sed pulvinar massa at ipsum rutrum luctus ultricies erat consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ultricies scelerisque diam, sed pretium elit facilisis in. Curabitur eget lorem sed mi dictum porta viverra id arcu. Nulla rutrum, turpis in vulputate cursus, ipsum ligula feugiat odio, vel hendrerit dui nulla nec arcu. Curabitur id leo elit, ac molestie ipsum.\n"
			<< "</p>\n"
			<< "<h2>2.2. Reference counted (not thread-safe)</h2>\n"
			<< "<p>\n"
			<< "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique, purus ac condimentum mollis, massa metus vehicula mauris, sed iaculis libero ipsum sit amet turpis. Quisque tincidunt adipiscing ante sed faucibus. Nulla quis lacus id nunc ullamcorper porta non eget ante. Phasellus elementum facilisis eros, at commodo augue imperdiet vel. Donec ac eros luctus nunc accumsan pretium. In quis lacus ipsum. Pellentesque et nibh nec metus tristique pellentesque et eu arcu. Morbi sed posuere urna. Maecenas bibendum ullamcorper nisl, eu convallis urna sollicitudin at. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum eget scelerisque ante. Nulla sed eros id nulla tempor dignissim. Nam id nisl eu sem condimentum vestibulum. Suspendisse ligula massa, imperdiet id varius at, dignissim ut enim.\n"
			<< "</p>\n"
			<< "<ul>\n"
			<< "	<li>PLorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique, purus ac condimentum mollis, massa metus vehicula</li>\n"
			<< "</ul>\n"
			<< "<pre class=\"brush: cpp; gutter: false; class-name: 'class_name_pre'\">\n"
			<< "#ifndef __YUNI_CORE_SYSTEM_CPU_H__\n"
			<< "# define __YUNI_CORE_SYSTEM_CPU_H__\n"
			<< "# include \"../../yuni.h\"\n"
			<< "namespace Yuni\n"
			<< "{\n"
			<< "namespace System\n"
			<< "{\n"
			<< "namespace CPU\n"
			<< "{\n"
			<< "	/*!\n"
			<< "	** \brief Get the number of system CPU\n"
			<< "	**\n"
			<< "	** \return The number of CPU (logic or not), 1 when the value is unknown\n"
			<< "	*/\n"
			<< "	unsigned int Count();\n"
			<< "} // namespace CPU\n"
			<< "} // namespace System\n"
			<< "} // namespace Yuni\n"
			<< "#endif // __YUNI_CORE_SYSTEM_CPU_H__\n"
			<< "</pre>\n"
			<< "<p>\n"
			<< "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tristique, <code>purus ac condimentum</code> mollis, massa metus vehicula mauris.\n"
			<< "</p>\n"
			<< "-->\n"
			<< "@{CONTENT}\n"
			<< "@{DIRECTORY_INDEX}\n"
			<< "</div> <!-- content -->\n"
			<< "<div class=\"modified\">\n"
			<< "Last modified : September 11, 2011\n"
			<< "</div>\n"
			<< "</td>\n"
			<< "<td></td>\n"
			<< "</tr>\n"
			<< "</table>\n"
			<< "<table class=\"footer\">\n"
			<< "<tr>\n"
			<< "<td style=\"width:240px;min-width:240px\"></td>\n"
			<< "<td class=\"footerlink right\">sitemap</td>\n"
			<< "<td class=\"footerlink\">\n"
			<< "<a href=\"@{ROOT}\">Yuni Framework</a>\n"
			<< "<a href=\"@{ROOT}/en/documentation\">Documentation</a>\n"
			<< "<a href=\"@{ROOT}/en/downloads\">Downloads</a>\n"
			<< "<a href=\"@{ROOT}/en/links\">Links</a>\n"
			<< "<a href=\"@{ROOT}/en/contacts\">Contacts</a>\n"
			<< "<a href=\"@{ROOT}/en/sitemap\">Sitemap</a>\n"
			<< "</td>\n"
			<< "<td class=\"footerlink right\">Documentation</td>\n"
			<< "<td class=\"footerlink\">\n"
			<< "<a href=\"@{ROOT}/en/documentation/v0.2/user/\">User's manual (v0.2)</a>\n"
			<< "<a href=\"@{ROOT}/en/documentation/v0.2/doxygen\">Doxygen (v0.2)</a>\n"
			<< "<a href=\"@{ROOT}/en/documentation/trunk/user/\">User's manual (trunk)</a>\n"
			<< "<a href=\"@{ROOT}/en/documentation/trunk/doxygen\">Doxygen (trunk)</a>\n"
			<< "</td>\n"
			<< "<td></td>\n"
			<< "</tr>\n"
			<< "</table>\n"
			<< "</div>\n"
			<< "<script type=\"text/javascript\">\n"
			<< "jQuery.fn.jBreadCrumb.defaults.easing = 'linear';\n"
			<< "jQuery(document).ready(function()\n"
			<< "{\n"
			<< "	jQuery(\"#breadCrumb0\").jBreadCrumb();\n"
			<< "})\n"
			<< "</script>\n"
			<< "<script type=\"text/javascript\">SyntaxHighlighter.all();</script>\n"
			<< "</body>\n"
			<< "</html>\n"
			;
	}



} // anonymous namespace


