#ifndef __YUNI_PLATFORM_CHECKS_H__
# define __YUNI_PLATFORM_CHECKS_H__

/* This file is generated by CMake */


/* stdio.h */
#cmakedefine YUNI_HAS_STDIO_H

/* string.h - memcmp, memcmpy... */
#cmakedefine YUNI_HAS_STRING_H


/* C++0x support by gcc (-std=c++0x) */
#cmakedefine YUNI_HAS_CPP0X_SUPPORT



/* Have long types - different from int */
#cmakedefine YUNI_HAS_LONG

/* Have int64_t, from stdint.h */
#cmakedefine YUNI_HAS_INT64_T

/* Have int128_t, from stdint.h */
#cmakedefine YUNI_HAS_INT128_T




#endif /* __YUNI_PLATFORM_CHECKS_H__ */
