#ifndef __NANY_AST_ALL_H__
# define __NANY_AST_ALL_H__

# include "node.h"
# include "programnode.h"
# include "unitdeclarationnode.h"
# include "declarationlistnode.h"
# include "functiondeclarationnode.h"
# include "scopenode.h"
# include "ifexpressionnode.h"
# include "expressionlistnode.h"
# include "parallelexpressionnode.h"
# include "typeexpressionnode.h"
# include "assignmentexpressionnode.h"
# include "equalexpressionnode.h"
# include "notequalexpressionnode.h"
# include "inferiorexpressionnode.h"
# include "inferiorequalexpressionnode.h"
# include "superiorexpressionnode.h"
# include "superiorequalexpressionnode.h"
# include "plusexpressionnode.h"
# include "minusexpressionnode.h"
# include "multiplyexpressionnode.h"
# include "divideexpressionnode.h"
# include "modulusexpressionnode.h"
# include "isexpressionnode.h"
# include "asexpressionnode.h"
# include "returnexpressionnode.h"
# include "identifiernode.h"
# include "literalnode.h"

#endif // __NANY_AST_ALL_H__
