#ifndef __YUNI_TOOLBOX_TREE_N_ITERATOR_UNDEF_H__
# define __YUNI_TOOLBOX_TREE_N_ITERATOR_UNDEF_H__


# undef YUNI_TOOLBOX_TREE_N_ITERATOR_PRE

# undef YUNI_TOOLBOX_TREE_N_ITERATOR_COMMON_PUBLIC_METHODS

# undef YUNI_TOOLBOX_TREE_N_ITERATOR_PROTECTED


#endif // __YUNI_TOOLBOX_TREE_N_ITERATOR_DEF_H__
