

#
# Irrlicht
#
MACRO(DEVPACK_IMPORT_IRRLICHT)
	IF(YUNI_EXTERNAL_3D_IRRLICHT)
		IF(APPLE)
			DEVPACK_IMPORT("irrlicht" "1.4.2" "3" "macos" "ub" "${DEVPACK_COMPILER}" "all")
		ENDIF(APPLE)
		IF(WIN32)
			DEVPACK_IMPORT("irrlicht" "1.4.2" "3" "windows" "${DEVPACK_ARCH}" "${DEVPACK_COMPILER}" "debug")
		ENDIF(WIN32)
		LIST(APPEND YUNI_STATIC_GFX3D "${YUNI_EXT_IRRLICHT_LIB}")
		LIST(APPEND YUNI_INCLUDE   "${YUNI_EXT_IRRLICHT_INCLUDE}")
	ENDIF(YUNI_EXTERNAL_3D_IRRLICHT)
ENDMACRO(DEVPACK_IMPORT_IRRLICHT)


#
# Ogre
#
MACRO(DEVPACK_IMPORT_OGRE)
	IF(YUNI_EXTERNAL_3D_OGRE)
		IF(APPLE)
			DEVPACK_IMPORT("ogre" "1.6.2" "1" "macos" "ub" "${DEVPACK_COMPILER}" "all")
		ENDIF(APPLE)
		IF(WIN32)
			DEVPACK_IMPORT("ogre" "1.6.2" "1" "windows" "${DEVPACK_ARCH}" "${DEVPACK_COMPILER}" "all")
		ENDIF(WIN32)
		LIST(APPEND YUNI_STATIC_GFX3D "${YUNI_EXT_OGRE_LIB}")
		LIST(APPEND YUNI_INCLUDE   "${YUNI_EXT_OGRE_INCLUDE}")
	ENDIF(YUNI_EXTERNAL_3D_OGRE)
ENDMACRO(DEVPACK_IMPORT_OGRE)



#
# LUA
#
MACRO(DEVPACK_IMPORT_LUA)
	IF(YUNI_EXTERNAL_SCRIPT_LUA)
		IF(APPLE)
			DEVPACK_IMPORT("lua" "5.1.4" "1" "macos" "ub" "${DEVPACK_COMPILER}" "all")
		ENDIF(APPLE)
		IF(MSVC)
			DEVPACK_SMART_IMPORT("lua" "5.1.4" "1" "all")
		ENDIF(MSVC)
		IF(IsLinux)
			DEVPACK_SMART_IMPORT("lua" "5.1.4" "1" "all")
		ENDIF(IsLinux)
		LIST(APPEND YUNI_STATIC_SCRIPT "${YUNI_EXT_LUA_LIB}")
		LIST(APPEND YUNI_INCLUDE   "${YUNI_EXT_LUA_INCLUDE}")
	ENDIF(YUNI_EXTERNAL_SCRIPT_LUA)
ENDMACRO(DEVPACK_IMPORT_LUA)



#
# PThreads
#
MACRO(DEVPACK_IMPORT_PTHREADS)
	IF(WIN32)
		DEVPACK_SMART_IMPORT("pthreads" "2.8.0" "3" "all")
		LIST(APPEND YUNI_STATIC_CORE "${YUNI_EXT_PTHREADS_LIB}")
		LIST(APPEND YUNI_INCLUDE   "${YUNI_EXT_PTHREADS_INCLUDE}")
	ENDIF(WIN32)
ENDMACRO(DEVPACK_IMPORT_PTHREADS)

