

MACRO(DEVPACK_IMPORT_IRRLICHT)
	IF(YUNI_EXTERNAL_3D_IRRLICHT)
		IF(APPLE)
			DEVPACK_IMPORT("irrlicht" "1.4.2" "2" "macos" "ub" "${DEVPACK_COMPILER}" "all")
		ENDIF(APPLE)
		IF(WIN32)
			DEVPACK_IMPORT("irrlicht" "1.4.2" "2" "windows" "${DEVPACK_ARCH}" "${DEVPACK_COMPILER}" "debug")
		ENDIF(WIN32)
		LIST(APPEND YUNI_LIBRARIES ${YUNI_EXT_IRRLICHT_LIB})
		LIST(APPEND YUNI_INCLUDE   ${YUNI_EXT_IRRLICHT_INCLUDE})
	ENDIF(YUNI_EXTERNAL_3D_IRRLICHT)
ENDMACRO(DEVPACK_IMPORT_IRRLICHT)


MACRO(DEVPACK_IMPORT_PTHREADS)
	IF(MSVC)
		DEVPACK_SMART_IMPORT("pthreads" "2.8.0" "2" "all")
		LIST(APPEND YUNI_LIBRARIES ${YUNI_EXT_PTHREADS_LIB})
		LIST(APPEND YUNI_INCLUDE   ${YUNI_EXT_PTHREADS_INCLUDE})
	ENDIF(MSVC)
ENDMACRO(DEVPACK_IMPORT_PTHREADS)
