#
# YUNI_INCLUDE
#

#
# The common paths for Yuni headers
#

LIST(APPEND YUNI_INCLUDE "${PROJECT_SOURCE_DIR}/..")


Set(YUNI_STATIC_CORE yuni-static-core)
Set(YUNI_STATIC_GFX3D yuni-static-gfx3d)

#
# Irrlicht
#
IF(YUNI_EXTERNAL_3D_IRRLICHT)
	DEVPACK_IMPORT_IRRLICHT()
ENDIF(YUNI_EXTERNAL_3D_IRRLICHT)

#
# PThreads
#
IF(YUNI_EXTERNAL_PTHREADS)
	DEVPACK_IMPORT_PTHREADS()
Endif(YUNI_EXTERNAL_PTHREADS)


