#
# YUNI_INCLUDE
#

#
# The common paths for Yuni headers
#

LIST(APPEND YUNI_INCLUDE "${PROJECT_SOURCE_DIR}/..")

IF(NOT YUNI_STATIC_CORE)
	Set(YUNI_STATIC_CORE yuni-static-core)
ELSE(NOT YUNI_STATIC_CORE)
	LIST(INSERT YUNI_STATIC_CORE 0 yuni-static-core)
ENDIF(NOT YUNI_STATIC_CORE)

IF(NOT YUNI_STATIC_GFX_CORE)
	Set(YUNI_STATIC_GFX_CORE yuni-static-gfx-core)
ELSE(NOT YUNI_STATIC_GFX_CORE)
	LIST(INSERT YUNI_STATIC_GFX_CORE 0 yuni-static-gfx-core)
ENDIF(NOT YUNI_STATIC_GFX_CORE)

IF(NOT APPLE AND NOT WIN32)
	LIST(APPEND YUNI_STATIC_GFX_CORE X11 Xrandr)
	LINK_DIRECTORIES("/usr/X11R6/lib")
ENDIF(NOT APPLE AND NOT WIN32)
IF(APPLE)
	FIND_LIBRARY(COREFOUNDATION_LIBRARY NAMES CoreFoundation)
	LIST(APPEND YUNI_STATIC_GFX_CORE "${COREFOUNDATION_LIBRARY}")
	FIND_LIBRARY(COCOA_LIBRARY NAMES Cocoa)
	LIST(APPEND YUNI_STATIC_GFX_CORE "${COCOA_LIBRARY}")
	FIND_LIBRARY(IOKIT_LIBRARY NAMES IOKit)
	LIST(APPEND YUNI_STATIC_GFX_CORE "${IOKIT_LIBRARY}")
ENDIF(APPLE)


Set(YUNI_STATIC_GFX3D  yuni-static-gfx3d)
Set(YUNI_STATIC_SCRIPT yuni-static-script)
Set(YUNI_STATIC_NET    yuni-static-net)


#
# Module Gfx3D
#
IF(YUNI_MODULE_GFX3D)
	# Irrlicht
	IF(YUNI_EXTERNAL_3D_IRRLICHT)
		DEVPACK_IMPORT_IRRLICHT()
	ENDIF(YUNI_EXTERNAL_3D_IRRLICHT)

	# Ogre 3D
	IF(YUNI_EXTERNAL_3D_OGRE)
		DEVPACK_IMPORT_OGRE()
	ENDIF(YUNI_EXTERNAL_3D_OGRE)
ENDIF(YUNI_MODULE_GFX3D)

#
# Script
#
IF(YUNI_MODULE_SCRIPT)

	#
	# Lua
	#
	IF(YUNI_EXTERNAL_SCRIPT_LUA)
		DEVPACK_IMPORT_LUA()
	ENDIF(YUNI_EXTERNAL_SCRIPT_LUA)

ENDIF(YUNI_MODULE_SCRIPT)

#
# PThreads
#
IF(YUNI_EXTERNAL_PTHREADS)
	DEVPACK_IMPORT_PTHREADS()
Endif(YUNI_EXTERNAL_PTHREADS)


