#
# YUNI_INCLUDE
#

#
# The common paths for Yuni headers
#
SET(YUNI_INCLUDE "${PROJECT_SOURCE_DIR}/..")

SET(YUNI_LIBRARIES  yuni-static)

IF(APPLE)
	LIST(APPEND YUNI_LIBRARIES  "-framework Cocoa")
ENDIF(APPLE)


#
# Irrlicht
#
IF(YUNI_EXTERNAL_3D_IRRLICHT)
	DEVPACK_IMPORT_IRRLICHT()
ENDIF(YUNI_EXTERNAL_3D_IRRLICHT)

#
# PThreads
#
IF(YUNI_EXTERNAL_PTHREADS)
	DEVPACK_IMPORT_PTHREADS()
Endif(YUNI_EXTERNAL_PTHREADS)


